### ISSUE TITLE
Auth instead of Database

### ISSUE THREAD

**Issue by SharmeenMomin** [SRN-SE-Fall24/CookSmart#3]
Instead of using the database to handle user authentication, the application should leverage a dedicated authentication service or middleware (such as Google, Firebase or a similar auth provider) to verify users' identities and manage their access.

**Comment by Rutvik2598** [comment]
Opened a PR https://github.com/SRN-SE-Fall24/CookSmart/pull/4 for this issue.

**Comment by nishadtardalkar** [comment]
I've merged the PR.
Remove the alerts of signup and login maybe?

**Comment by Rutvik2598** [comment]
Yes will remove those in a separate PR.
