### ISSUE TITLE
Ability to create a shopping list based on bookmarked recipes.

### ISSUE THREAD

**Issue by nishadtardalkar** [SRN-SE-Fall24/CookSmart#5]
Give users the ability to bookmark searched recipes (save them in DB to fetch later).
1. Maybe: From the bookmarks users can select recipes to create a shopping list from.
2. Maybe: Instead of selecting from bookmarks, everything in the bookmarks will be added to shopping list.

**Comment by Rutvik2598** [comment]
Created a [PR](https://github.com/SRN-SE-Fall24/CookSmart/pull/9) to store bookmarked recipes in the db.

**Comment by SharmeenMomin** [comment]
Created [PR](https://github.com/SRN-SE-Fall24/CookSmart/pull/11/) to fetch and display book marked recipes under user profile

**Comment by Rutvik2598** [comment]
Created [PR](https://github.com/SRN-SE-Fall24/CookSmart/pull/12) to display the shopping list for the bookmarked recipes.

**Comment by Rutvik2598** [comment]
Closing this issue as all PR's have been merged.
